apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  mongo-user: bW9uZ29Vc2Vy # Base64 encoded value of 'mongoUser'
  mongo-password: bW9uZ29wYXNzd29yZA== # Base64 encoded value of 'mongoPassword'